
-- Using the NYC Taxi public dataset (Yellow Trips) from Google BigQuery, complete the following exercises:
SELECT * FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2021` LIMIT 1000;



-- Exercise 1: Count the number of trips in January 2023
SELECT COUNT(vendor_id) FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2021`;

-- Exercise 2: Calculate the total revenue generated by taxi trips in 2023

SELECT SUM(total_amount) FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2021`;
-- Exercise 3: Find the most popular pickup location

SELECT pickup_location_id, COUNT(*) as count
FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2021`
GROUP BY pickup_location_id
ORDER BY count DESC;

-- Exercise 4: Analyze the number of trips per hour of the day
SELECT EXTRACT(HOUR FROM pickup_datetime) as h, COUNT(vendor_id) as c
FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2021`
GROUP BY h
ORDER by COUNT(vendor_id) DESC;

-- Exercise 5: Calculate the average trip distance
SELECT AVG(trip_distance)
FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2021`;

-- Exercise 6: Find the longest trip by distance
SELECT trip_distance
FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2021`
ORDER BY trip_distance DESC;

-- Exercise 7: Calculate the total number of passengers by payment type
SELECT payment_type, COUNT(*) as count
FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2021`
GROUP BY payment_type
ORDER BY count DESC;

-- Exercise 8: Find the most common drop-off location for trips paid by credit card
SELECT dropoff_location_id
FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2021`
WHERE payment_type = "1"
GROUP BY dropoff_location_id
ORDER BY COUNT(dropoff_location_id) DESC;

-- Exercise 9: Calculate the total number of trips that had more than 4 passengers
SELECT COUNT(vendor_id)
FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2021`
WHERE passenger_count > 4;


-- Exercise 10: Subquery - Find the average fare for trips longer than the average trip distance
SELECT AVG(total_amount)
FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2021`
WHERE trip_distance >(SELECT AVG(trip_distance)
FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2021`);

